# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Prueba Viper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestore'
  pod 'FirebaseDatabase'

  # Pods for Prueba Viper

end
